# Basics requeriments
- How to set the Conda environment
- How to import basic libraries 
- How to load pipeline
- How to download a model

In [1]:
1+1

2

In [2]:
print("Hi world!")

Hi world!

In [3]:
import numpy as np

In [4]:
import sys
print(sys.executable)

c:\Users\sanch\miniconda3\envs\MLops_training\python.exe

In [5]:
import azureml

In [6]:
print(azureml)

<module 'azureml' from 'c:\\Users\\sanch\\miniconda3\\envs\\MLops_training\\Lib\\site-packages\\azureml\\__init__.py'>

In [7]:
import transformers

In [8]:
print(transformers)

<module 'transformers' from 'c:\\Users\\sanch\\miniconda3\\envs\\MLops_training\\Lib\\site-packages\\transformers\\__init__.py'>

In [9]:
import datasets

In [10]:
print(datasets)

<module 'datasets' from 'c:\\Users\\sanch\\miniconda3\\envs\\MLops_training\\Lib\\site-packages\\datasets\\__init__.py'>

## Model usage

In [11]:
from transformers import pipeline

In [18]:
generator = pipeline("text-generation", model="gpt2")

config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

C:\Users\sanch\AppData\Roaming\Python\Python314\site-packages\huggingface_hub\file_download.py:138: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\sanch\.cache\huggingface\hub\models--gpt2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

model.safetensors:   0%|          | 0.00/548M [00:01<?, ?B/s]

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

In [19]:
generator("Summarize:DeepSeek-V4-Pro-Max, the maximum reasoning effort mode of DeepSeek-V4-Pro, significantly advances the knowledge capabilities of open-source models, firmly establishing itself as the best open-source model available today. It achieves top-tier performance in coding benchmarks and significantly bridges the gap with leading closed-source models on reasoning and agentic tasks. Meanwhile, DeepSeek-V4-Flash-Max achieves comparable reasoning performance to the Pro version when given a larger thinking budget, though its smaller parameter scale naturally places it slightly behind on pure knowledge tasks and the most complex agentic workflows.")

[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Ignoring clean_up_tokenization_spaces=True for BPE tokenizer GPT2Tokenizer. The clean_up_tokenization post-processing step is designed for WordPiece tokenizers and is destructive for BPE (it strips spaces before punctuation). Set clean_up_tokenization_spaces=False to suppress this warning, or set clean_up_tokenization_spaces_for_bpe_even_though_it_will_corrupt_output=True to force cleanup anyway.

[{'generated_text': 'Summarize:DeepSeek-V4-Pro-Max, the maximum reasoning effort mode of DeepSeek-V4-Pro, significantly advances the knowledge capabilities of open-source models, firmly establishing itself as the best open-source model available today. It achieves top-tier performance in coding benchmarks and significantly bridges the gap with leading closed-source models on reasoning and agentic tasks. Meanwhile, DeepSeek-V4-Flash-Max achieves comparable reasoning performance to the Pro version when given a larger thinking budget, though its smaller parameter scale naturally places it slightly behind on pure knowledge tasks and the most complex agentic workflows. DeepSeek-V4-Flex-Max is the first version to support an agentic approach in the open source realm. It utilizes the state of the art Intel® Optane™ graphics processing unit and the fast, flexible Intel® Optane™ Memory™ architecture. The F-DIMM processor is supported by the NVIDIA® Tegra™ 1.1c and NVIDIA® Tegra II™ processors, and provides a complete processor solution that uses a full-featured GPU with up to 4 GB of RAM, a fully integrated memory interface and support for up to 64 GB of memory bandwidth.\n\nThe F-DIMM processor is supported by the NVIDIA® Tegra™ 1.1c and NVIDIA® Tegra II™ processors, and provides a complete processor solution that uses a full-featured GPU with up to 4 GB of RAM, a fully integrated memory interface and support for up to 64 GB of memory bandwidth. The F-DIMM GPU offers the power to accelerate graphics processing on a single GPU. The F-DIMM GPU enables the performance enhancement of the NVIDIA® Tegra™ 1.1c and NVIDIA® Tegra II processors with up to 48 GB of memory bandwidth. It is supported on the NVIDIA GeForce'}]

In [20]:
generator("translate English to Italian: I really like this product, it solved everything I needed")

[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[{'generated_text': "translate English to Italian: I really like this product, it solved everything I needed for my new home, and it's fast and easy to use.\n\nRated 5 out of 5 by TK from Good product - great for my home kitchen! I came home with a set of new dishes which I had always wanted to put on the counter and put somewhere to put them. I went to the store and bought the 3rd set of dishes. I didn't like the layout and the kitchen was a mess, but the customer service was so helpful that I was able to get the dishes that I needed. The 2nd set of dishes was about $1.50 because the one that I did have had to buy the other set was smaller. The kitchen that I had purchased was a big mess and it was hard to get everything together. I would highly recommend this product. I recommend the 3rd set of dishes to anyone that wants to use a larger kitchen.\n\nRated 5 out of 5 by Anonymous from Great product, really the best of the best I bought this dishwasher and it worked really well! It was easy to do and was easy to clean. I was surprised at how much of a hassle it was to clean the dishwasher. I was also surprised how much of a hassle it would be to get the dishwasher to clean itself"}]

## Datasets

In [1]:
from datasets import load_dataset

In [2]:
movie_rat = load_dataset("ernestum/TestDataset")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/508 [00:00<?, ?B/s]

C:\Users\sanch\AppData\Roaming\Python\Python314\site-packages\huggingface_hub\file_download.py:138: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\sanch\.cache\huggingface\hub\datasets--ernestum--TestDataset. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

data/train-00000-of-00001-795fc88cd88168(…):   0%|          | 0.00/18.7k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/12 [00:00<?, ? examples/s]

In [3]:
movie_rat

DatasetDict({
    train: Dataset({
        features: ['obs', 'acts', 'infos', 'terminal', 'rews'],
        num_rows: 12
    })
})

In [4]:
train = movie_rat["train"]
df = train.to_pandas()

In [5]:
df.describe()

,obs,acts,infos,terminal,rews
count,12,12,12,12,12
unique,12,12,12,1,12
top,"[[-0.44839054, 0.0], [-0.44994983, -0.00155928...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[{}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {...",True,"[-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1...."
freq,1,1,1,12,1

In [6]:
df.head()

,obs,acts,infos,terminal,rews
0,"[[-0.44839054, 0.0], [-0.44994983, -0.00155928...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[{}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {...",True,"[-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1...."
1,"[[-0.57485646, 0.0], [-0.5734736, 0.0013829195...","[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ...","[{}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {...",True,"[-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1...."
2,"[[-0.52076095, 0.0], [-0.51978225, 0.000978716...","[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ...","[{}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {...",True,"[-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1...."
3,"[[-0.5463389, 0.0], [-0.5451685, 0.0011704187]...","[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ...","[{}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {...",True,"[-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1...."
4,"[[-0.4702858, 0.0], [-0.46968395, 0.0006018553...","[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, ...","[{}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {...",True,"[-1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1...."